### NumPy Array

In [1]:
import numpy as np

#### Introduction

#### example01

In [2]:
x = np.array([1, 2, 3, 4])
print(x)

[1 2 3 4]


#### example02

In [3]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x[1][2])

print(x.ndim) #anzahl dimensionen
print(x.size) #anzahl der elemente
print(x.shape) #matrix-form
print(x.reshape(3, 3, 1)) #macht aus 2 dimensionen 3
print(x.reshape(3, 3, 1).ndim)

6
2
9
(3, 3)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
3


#### example03

In [4]:
x = np.array([2,1,3])

x = np.append(x,1) #fügt element hinzu
print(x)

x = np.delete(x,0) #entefernt element an position 'zahl'
print(x)

x = np.sort(x) #sortiert aufsteigend
print(x)

x = np.arange(2, 10, 3) #beginn bei 2, jedes 3.element exklusive rand 10
print(x)

[2 1 3 1]
[1 3 1]
[1 1 3]
[2 5 8]


#### test01

You are given an array that holds the square footage data for houses on a particular street.
A new house has just been constructed on that street.
Modify your program to take the new house value as input, add it to the array, and output the array sorted in ascending order. 

In [5]:
data = np.array([1000, 2500, 1400, 1800, 900, 4200, 2200, 1900, 3500])

data = np.append(data, int(input()))

data = np.sort(data)

print(data)

2000
[ 900 1000 1400 1800 1900 2000 2200 2500 3500 4200]


#### exercise01

In [37]:
x = np.arange(2, 8, 2)

x = np.append(x, x.size)

x = np.sort(x)

print(x[1])

3


#### Shape

#### example01

In [7]:
x = np.arange(1, 7) #1 dimension
print(x)
print(x.ndim)

x = x.reshape(3, 2) #2 dimensions => 6 = 3 reihen + 2 spalten
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2


#### example02

In [8]:
x = np.array([[1,2], [3,4], [5,6]]) #2 dimensions
print(x)

z = x.reshape(6) #1 dimension
print(z)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


#### excercise01

In [9]:
x = np.arange(1, 8, 3)
print(x)

z = x.reshape(3, 1)
print(z[1][0])

[1 4 7]
4


#### test01
You are given an array that represents the occupancy of seats in a movie theater. A seat marked with 1 is occupied, while one marked 0 means the seat is free.
However, the array is flat and 1-dimensional. Transform it into a 2-dimensional array, representing the rows of the seats.
Each row in the theater has 5 seats and there are a total of 30 seats.
Reshape the array into the corresponding shape and output the row at the given index, which is taken from user input. 

In [10]:
data = np.array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0])

row = int(input())

reshaper = data.reshape(6,5)
#print(reshaper)
print(reshaper[row, :])




2
[1 1 1 1 1]


#### Indexing and Slicing

#### example01

In [11]:
x = np.arange(1, 10)

print(x[0:2])
print(x[5:])
print(x[:2])
print(x[-3:])

[1 2]
[6 7 8 9]
[1 2]
[7 8 9]


#### example02

In [12]:
x = np.arange(1, 10)
print(x[x<4])

[1 2 3]


In [13]:
print(x[(x>5) & (x%2 == 0)])

[6 8]


#### test01
You are given a task to find all of the whole numbers below 100 that are multiples of both 3 and 5.
Create an array of numbers below 100 that are multiples of both 3 and 5, and output it. 

In [14]:
x = np.arange(1, 100)
print(x[(x%5==0) & (x%3==0)])

[15 30 45 60 75 90]


#### excercise01

In [15]:
x = np.array([11,42,8,5,18])
z = x[x > 15]
print(z.size)

2


#### Array Operations

#### example01

In [16]:
x = np.arange(1, 10)
print(x.sum())

45


In [17]:
x = np.arange(1, 10)
print(x)
y = x*2 #alle elemente *2
print(y)

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


#### exercise01

In [18]:
data_mb = np.array([6, 3, 10, 143])
data_kb = data_mb * 1024
print(data_kb.max())

146432


#### example02

In [19]:
x = np.array([14, 18, 19, 24, 26, 33, 42, 55, 67])

print(np.mean(x))
print(np.median(x))
print(np.var(x))
print(np.std(x))

33.111111111111114
26.0
292.5432098765432
17.10389458212787


#### test01
The given array represents the daily number of infections for 30 days.
Find out how many days exceeded the average number of infections. 

In [30]:
data = np.array([120, 98, 150, 65, 42, 100, 190, 220, 140, 110, 88, 89, 100, 120, 50, 180, 155, 42, 89, 77, 200, 190, 125, 98, 77, 40, 39, 59, 30, 67])

z = np.sum(data)/np.size(data) #kürzer: np.mean(data)
result = data[data>z]
print(result.size)

12


#### Quiz

#### exercise01

In [21]:
x = np.arange(3, 9)
z = x.reshape(2, 3)
print(z[1][1])

7


#### exercise02

In [22]:
x = np.arange(1, 50)
res = x[x>42]
print(res)

[43 44 45 46 47 48 49]


#### exercise03

In [23]:
z = x[x>np.mean(x)]
print(z)

[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### exercise04

In [24]:
x = np.arange(1,5)
x = x*2
print(x[:3].sum())

12


#### test01
You are given an array that represents house prices.
Calculate and output the percentage of houses that are within one standard deviation from the mean. 

In [25]:
data = np.array([150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000])

print(np.std(data))
calc = np.mean(data) - np.std(data)
print(calc)

l = []
for i in data:
    if i < calc:
        l.append(i)
print((len(l)/len(data))*100)

130053.69984644804
130258.80015355196
18.75
