In [6]:
import numpy as np

array = np.array([[1,2,3.5], [1,3, 4]])
print(array)
print(array.ndim)

[[1.  2.  3.5]
 [1.  3.  4. ]]
2


In [9]:
array = np.arange(27)
print(array)
array2 = np.arange(27).reshape(3, 3, 3)
print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [19]:
array = np.random.randint(0, 10, (4, 4))
smaller = array < 5
print(smaller)

[[ True  True False False]
 [ True False  True False]
 [ True False False False]
 [False  True False False]]


In [23]:
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(vector)
shapey = vector.reshape([2, 4]) #2 zeilen, 4 spalten
print(shapey)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
