#### A linear Model for Classification
- equation
- Beispiel: Diagramm mit durchgezogener Linie Alter, Verpflegung, c=überlebt
- Punkte links der durchgezogenen Linie: ertrunken (Wert negativ)
- Punkte rechts der durchgezogenen Linie: überlebt (Wert positiv)

#### Build a Logistic Regression Model with Sklearn

In [ ]:
import pandas as pd

Daten auslesen

In [ ]:
df = pd.read_csv('https://sololearn.com/uploads/files/titanic.csv')

#alle zeilen zuerst numerisch machen -> wird zu boolean
df['male'] = df['Sex'] == 'male'

#x als array, das die gewünschten spalten auswählt
x = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values

#eigentliches ziel 'survived' wird als y deklariert
y = df['Survived'].values

print(x) #gewünschte spalten
print(y) #die überlebenden als 0 und 1

Sklearn verwenden

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
#klasse initiieren
model = LogisticRegression() 

#x(feature matrix) und y(target array) festlegen
x = df[['Fare', 'Age']].values
y = df['Survived'].values

#model erzeugen über fit()-methode
model.fit(x, y)

#zeile auswählen, die am besten passt über die koeffizienten .coef_ und intercept_
#ergebnis ist gleichung für equation-linie: Wert1*x + Wert2 *y + Wert3
print(model.coef_, model.intercept_)

Vorhersagen mithilfe des Modells machen

In [ ]:
x = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values
model = LogisticRegression()
model.fit(x, y)

#predict() macht vorhersagen
model.predict(x)

#vorhersage, dass der (werte hier von erstem passagier) erste passagier überlebt
print(model.predict([[3, True, 22.0, 1, 0, 7.25]]))

#vorhersage für die ersten 5 reihen
print(model.predict(x[:5])) #erste 5 daten-reihen
print(y[:5]) #erste 5 werte des ziels

Score eines Modells überprüfen

In [ ]:
#array erstellen, das vorhersagbare werte enthält
y_pred = model.predict(x)

#erstellt ein array mit boolean-werten, ob modell jeden passagier korrekt vorhergesagt hat
y == y_pred

#anzahl der true-werte ausgeben über sum()
print((y==y_pred).sum())
#ergebnis: 714 => modell macht korrekte vorhersage

#korrekte prozentzahl ausgeben durch teilen durch alle passagiere dank y.shape[0]
#ergebnis: unser 'accuracy score'
print((y==y_pred).sum() / y.shape[0])

#### Logistic Regression with the Breast Cancer Dataset

In [ ]:
#daten-set, das bereits in sklearn drin ist, daher kein csv-import nötig
from sklearn.datasets import load_breast_cancer
cancer_data = load_breast_cancer()

Datenset untersuchen

In [ ]:
#zeigt keys des daten-sets an
print(cancer_data.keys())

#DESCR beschreibt daten-set genauer
print(cancer_data['DESCR'])

Daten in Pandas laden

In [ ]:
#numpy array conversion nach folgendem schema
cancer_data['data']

#array-grö0e nach zeilen und spalten ausgeben lassen über .shape
cancer_data['data'].shape

In [ ]:
#ruft spaltennamen auf
cancer_data['feature_names']

#erstellt dataframe mimt allen feature datas
df = pd.DataFrame(cancer_data['data'], columns=cancer_data['feature_names'])
print(df.head())

In [ ]:
#ziel ins data frame mit aufnehmen
print(cancer_data['target'])

#datenpunkte checken
cancer_data['target'].shape

Regression Model generieren

In [9]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression

#daten-set, das bereits in sklearn drin ist, daher kein csv-import nötig
from sklearn.datasets import load_breast_cancer
cancer_data = load_breast_cancer()

#zeigt keys des daten-sets an
print(cancer_data.keys())

#DESCR beschreibt daten-set genauer
print(cancer_data['DESCR'])

#numpy array conversion nach folgendem schema
cancer_data['data']

#array-grö0e nach zeilen und spalten ausgeben lassen über .shape
cancer_data['data'].shape

#ruft spaltennamen auf
cancer_data['feature_names']

#erstellt dataframe mimt allen feature datas
df = pd.DataFrame(cancer_data['data'], columns=cancer_data['feature_names'])
#print(df.head())
df['target'] = cancer_data['target']

#ziel ins data frame mit aufnehmen
print(cancer_data['target'])

#datenpunkte checken
cancer_data['target'].shape

#feature matrix x und target array y aufbauen
x = df[cancer_data.feature_names].values
y = df['target'].values

#object für logistic regression und model aufbauen
"""model = LogisticRegression()
model.fit(x, y)"""

#schnelleren algorithmus festlegen über solver
model = LogisticRegression(solver='liblinear')
model.fit(x, y)

#model-vorhersage für ersten datenpunkt bestimmen, achtung: 2d-array [x[0]]
print('prediction for datapoint 0:', model.predict([x[0]]))

#wie das model bezogen auf den ganzen datensatz funktioniert
print(model.score(x, y))

#ergebnis: 96% der datenpunkte sind korrekt gesetzt, model hat eine zu 96% korrekte vorhersage getroffen

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])
.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were c

Nochmal unkommentiert ...

In [10]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression

cancer_data = load_breast_cancer()
df = pd.DataFrame(cancer_data['data'], columns=cancer_data['feature_names'])
df['target'] = cancer_data['target']

X = df[cancer_data.feature_names].values
y = df['target'].values

model = LogisticRegression(solver='liblinear')
model.fit(X, y)
print("prediction for datapoint 0:", model.predict([X[0]]))
print(model.score(X, y))

prediction for datapoint 0: [0]
0.9595782073813708


Vorhersage für einzelnen Datenpunkt machen

In [17]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np


n = int(input())
X = []
for i in range(n):
    X.append([float(x) for x in input().split()])
y = [int(x) for x in input().split()]
datapoint = [float(x) for x in input().split()]

df = pd.DataFrame(X)
#print(df)

6
1 3
3 5
5 7
3 1
5 3
7 5
1 1 1 0 0 0
2 4


In [18]:
X_arr = df.values
print(X_arr, type(X_arr), X_arr.shape)

[[1. 3.]
 [3. 5.]
 [5. 7.]
 [3. 1.]
 [5. 3.]
 [7. 5.]] <class 'numpy.ndarray'> (6, 2)


In [19]:
y_arr = np.array(y)
print(y_arr, type(y_arr), y_arr.shape)

[1 1 1 0 0 0] <class 'numpy.ndarray'> (6,)


In [20]:
arr_datapoint = np.array(datapoint)
print(arr_datapoint, arr_datapoint.shape)

[2. 4.] (2,)


In [21]:
model = LogisticRegression()
model.fit(X_arr, y_arr)
print(model.predict(X))

[1 1 1 0 0 0]


In [22]:
result = model.predict([arr_datapoint])
print(type(result), int(result[0]))

<class 'numpy.ndarray'> 1


In [24]:
print(model.score(X_arr, y_arr))

1.0
